language: java
jdk:
- openjdk6
before_script:
- mysql -e 'create database FIWARE_SETTLEMENT;'
- mysql -u root FIWARE_SETTLEMENT < ./rss-core/resources/datamodel/tests/dbmodel.sql
- echo "USE FIWARE_SETTLEMENT;\nshow tables;\n" | mysql -u root
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH
  PRIVILEGES;\n" | mysql -u root
install:
- mvn clean install -DskipTests=true -B -V -q
test:
- mvn test -B -q -fae

env:
  global:
  - COVERALLS_SERVICE_NAME=travis-ci
  # COVERALLS_REPO_TOKEN (encrypted)
  - secure: t56Q+wOTRzBDTdJI+nW8xjmyOhCKQdHrQ0KKw9aLEscDC613TJ5kMYziM8VcPpNqGm+H9rxjthJE09T5yZcKqbEk8/9MEghYoH+a4N4xtqaGbDU4min2SVl/xIa44NInT77s16XigKpJ/VnDGzcu1dgpOJFGVw7IwNa3eSDa9l0=
  
after_success:
- mvn cobertura:cobertura coveralls:cobertura

  
